--- #YAML:1.0
name:               PDF-Table
version:            0.9.6
abstract:           A utility class for building table layouts in a PDF::API2 object.
author:
    - Desislav Kamenov <desi@zendor.eu>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:  https://github.com/kamenov/PDF-Table/issues
    repository:  https://github.com/kamenov/PDF-Table
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
