# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDF-Table
version:      0.02
version_from: lib/PDF/Table.pm
installdirs:  site
requires:
    PDF::API2:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
